name: Build and Deploy Application

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/MVPCustomFileChecker.yml'  # Trigger on changes to this workflow file
      - 'MVPCustomCheckerLibrary/**'
      - 'MVPCustomCheckerProcessor/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Adjust according to your project's requirements

    - name: Restore dependencies
      run: dotnet restore $GITHUB_WORKSPACE/MVPCustomCheckerBot.sln

    - name: Create deployment directory
      run: |
        echo ${{ secrets.SUDOPWD }} | sudo -S mkdir -p /var/MVPCustomCheckerProcessor/
        echo ${{ secrets.SUDOPWD }} | sudo -S chown $USER:$USER /var/MVPCustomCheckerProcessor/

    - name: Build and Publish Project
      run: |
        dotnet publish $GITHUB_WORKSPACE/MVPCustomCheckerProcessor/MVPCustomCheckerProcessor.csproj -c Release -o /var/MVPCustomCheckerProcessor

    - name: Update Cron Job to Run the Application
      run: |
        (crontab -l 2>/dev/null; echo "*/5 * * * * /home/tristan/.dotnet/dotnet /var/MVPCustomCheckerProcessor/MVPCustomCheckerProcessor.dll >> /var/MVPCustomCheckerProcessor/app.log 2>&1") | crontab -


